services:
  - type: web
    name: charts
    runtime: node
    plan: free
    rootDir: charts/frontend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
